name: CI

on:
  push:
    branches: [main, master]
    paths:
      - "ffwf/**"
      - "src/**"
      - "pyproject.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "tests/**"
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "ffwf/**"
      - "src/**"
      - "pyproject.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "tests/**"

# Cancel in-progress runs when a new push is made to the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }} / py-${{ matrix.python-version }}
    # Only run if the PR is not a draft
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Build and install
        run: |
          # Adding native flags to squeeze performance in tests
          export RUSTFLAGS="-C target-cpu=native"
          uv venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "PATH=.venv/bin:$PATH" >> $GITHUB_PATH
          uv pip install maturin
          uv run maturin develop --release
        shell: bash

      - name: Run tests
        run: |
          uv pip install -e ".[dev]"
          uv run pytest --ignore=tests/test_oom.py
        shell: bash
